image: node:lts-slim
image: markhobson/node-chrome

stages:
    - build
    - lint
    - deploy
    - run_lighthouse

build:
    stage: build
    tags:
        - docker
    artifacts:
        paths:
            - __sapper__
            - src/node_modules/@sapper
        expire_in: 1 week
    script: 
        - npm ci
        - npm run build

lint:
    stage: lint
    tags:
        - docker
    dependencies: 
        - build
    script: 
        - npm i
        - npm run lint

deploy:
    type: deploy
    stage: deploy
    tags:
        - docker
    image: ruby:latest
    script:
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
        - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
    only:
        - master

run_lighthouse:
    variables:
        LIGHTHOUSE_TEST_URL: https://veg-web.herokuapp.com/
    stage: run_lighthouse
    only:
        - master
    before_script:
        - npm i -g lighthouse
    script:
        - lighthouse --chrome-flags="--headless --no-sandbox" $LIGHTHOUSE_TEST_URL --output html --output-path ./report.html
    artifacts:
        paths:
            - ./report.html
        expire_in: 1 week
