image: node:latest

cache:
  paths:
    - node_modules/
    - __sapper__
    - src/node_modules/@sapper

stages:
    - build
    - lint
    - deploy

build:
    stage: build
    tags:
        - docker
    script: 
        - npm i
        - npm run build

lint:
    stage: lint
    tags:
        - docker
    script: 
        - npm run lint

deploy:
    type: deploy
    stage: deploy
    tags:
        - docker
    image: ruby:latest
    script:
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
        - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
    only:
        - master