image: node:latest

before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl

stages:
    - build
    - deploy

build:
    stage: build
    script: npm i --only=prod
    script: npm run build

deploy:
    type: deploy
    stage: deploy
    image: ruby:latest
    script:
        - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
    only:
        - master