image: node:lts-slim

stages:
    - build
    - lint
    - deploy

build:
    stage: build
    tags:
        - docker
    artifacts:
        paths:
            - __sapper__
            - src/node_modules/@sapper
        expire_in: 1 week
    script: 
        - npm ci
        - npm i --save-dev sapper
        - npm run build

lint:
    stage: lint
    tags:
        - docker
    dependencies: 
        - build
    script: 
        - npm i
        - npm run lint

deploy:
    type: deploy
    stage: deploy
    tags:
        - docker
    image: ruby:latest
    script:
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
        - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
    only:
        - master
