export const ORGANIZATION_NAME = 'MyFoodCoop'
export const POINT_OF_SALES_INACTIVITY_TIMEOUT_IN_MINUTES = 10;
export const POINT_OF_SALES_MAX_LOGIN_TIME_IN_MINUTES = 30;
export const LEGAL_NOTICE_LINK = '';